### ISSUE TITLE
Doesn't work on nodejs v14.1.0

### ISSUE THREAD

**Issue by shunz19** [ExodiusStudios/node-tmux#1]
I installed the module using `npm install --save node-tmux` in my

>Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

and when I tried to import the module:

> import {tmux} from 'node-tmux';
        ^^^^
SyntaxError: The requested module 'node-tmux' does not provide an export named 'tmux'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)

Then I tried 

> import * as tmux from 'node-tmux';
console.log(tmux)
tmux().then(tm => { ...

Which resulted to:

> [Module] {
  default: { Tmux: [Function: Tmux], tmux: [Function: tmux] }
}
file:///home/test/mcn/index.js:6
tmux().then(tm => {
^
TypeError: tmux is not a function

Even tho i tried using

> tmux.default.tmux().then(tm => { ...

I still couldn't get an instance
